name: Build and Push Frontend & Backend to Docker Hub

on:
  push:
    branches: [main]
    paths:
      - "express-backend/**"
      - "frontend/**"

env:
  BACKEND_IMAGE_NAME: siddjuugi/kinumna-backend
  FRONTEND_IMAGE_NAME: siddjuugi/kinumna-frontend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./express-backend
          file: ./express-backend/Dockerfile.prod
          push: true
          no-cache: true
          tags: |
            ${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ env.BACKEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  build-frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Build Args
        run: |
          echo "Building frontend with:"
          echo "NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}"

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          no-cache: true
          build-args: |
            NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }}
          tags: |
            ${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.FRONTEND_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
